language: android

jdk: oraclejdk8

sudo: required # For faster internet speeds and more memory

env:
  global:
    - ANDROID_TARGET=android-19
    - ANDROID_ABI=armeabi-v7a

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-19
    - android-25
    - android-26
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-google_apis-19
    - sys-img-armeabi-v7a-google_apis-25
  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-.+
    - '.+'

branches:
  except:
    - gh-pages

notifications:
  email: false
  slack:
    secure: Xppx9rgIKz/iRa+m9dfbkDCVOY6NtKHB6s07pUnpbAqyi/c8LJ5ls7r+mtna5oY/1Q6biuPW+DY7CMpleT0HDIN1T3GAvxqYu/rRklkyPK6O/aPSKUEWtPjKdZ5sJ+xhRYAlU6uOesaYFUShG1jaC+G5d34g5IiMeE/wX17xrg5W4wzoXHsFn44lqOUJvwTw+Nmp/GdzfFkpcNYHI9fHFvFPPRMFvk/9d6bFXVLjtKtVfIxWxzblIVikkZXNggxnuXYIQho5S/OZL/lk+nfnwCWzxsODRS/ZiDZ+SWGzZx5yk1SBAqEKK5bO4+ActDW8pw4sGfp5gTofwqfGBIbMnwVnIxi2EHkrZtrNSPy/uzBdVJJMRqVzaSpdrgvZ6E34GmV+eBH9j1zJ9CZw9pozd/dy4Cz0yKGWWt60TtSRZSqC3ytjX8A1LF3/B5+hS/AwCmva3SGzJUY6HVhwO7D5aeF4gYhAxgLZL63Mn/KaeiRTHWQR/h9MEQKlLlHC5y9XdctBRNsITNWpDMvPE+LPvYbLFVT8S6ujTaUNnnXjrvF78E2r+ttKs6xqgHkNl0U38aPAmIorb3su/s5tUSRRKVag0QYMtJHgDvwOpUCRpJdgyUOhSQ1CqtoxZpbicFdN3+7dJIzNabS5HOdwP4BHihaKDEtuTFk91w7X4fz3KIg=

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - echo y | ${ANDROID_HOME}tools/bin/sdkmanager "build-tools;26.0.2" #remove when travis will support build tools 26.0.2
  - echo y | ${ANDROID_HOME}tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo y | ${ANDROID_HOME}tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
    # Create and start an emulator for instrumentation tests.
  - android list targets
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -noaudio -no-window &
#  - avdmanager list
#  - echo no | ${ANDROID_HOME}tools/bin/avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"
#  - $ANDROID_HOME/tools/emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - adb shell input keyevent 82 &

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)